from __future__ import annotations
from PyQt5 import QtCore, QtGui, QtWidgets
import home_page
import login
import mysql.connector as mc
from PyQt5.QtWidgets import QMessageBox

global user

class Ui_form_pengajuan(object):

    def openHomePageFromFormPengajuan(self):
        self.home_page = QtWidgets.QWidget()
        self.ui = home_page.Ui_home_page()
        self.ui.setupUiHomePage(self.home_page)
        self.home_page.show()





    def setupUiFormPengajuan(self, form_pengajuan):
        form_pengajuan.setObjectName("form_pengajuan")
        form_pengajuan.resize(619, 375)
        form_pengajuan.setStyleSheet("background-color: rgb(117, 177, 124);")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(form_pengajuan)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_5 = QtWidgets.QLabel(form_pengajuan)
        self.label_5.setStyleSheet("background-color: rgb(72, 213, 11);")
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_3.addWidget(self.label_5)
        self.line = QtWidgets.QFrame(form_pengajuan)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_3.addWidget(self.line)
        self.verticalLayout.addLayout(self.verticalLayout_3)
        spacerItem = QtWidgets.QSpacerItem(20, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_6 = QtWidgets.QLabel(form_pengajuan)
        self.label_6.setStyleSheet("font: 75 9pt \"Arial\";")
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_5.addWidget(self.label_6)
        spacerItem1 = QtWidgets.QSpacerItem(37, 17, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem1)
        self.lineEdit_nama = QtWidgets.QLineEdit(form_pengajuan)
        self.lineEdit_nama.setStyleSheet("background-color: rgb(190, 190, 190);")
        self.lineEdit_nama.setObjectName("lineEdit_nama")
        self.horizontalLayout_5.addWidget(self.lineEdit_nama)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        spacerItem2 = QtWidgets.QSpacerItem(20, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_7 = QtWidgets.QLabel(form_pengajuan)
        self.label_7.setStyleSheet("font: 75 9pt \"Arial\";")
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_6.addWidget(self.label_7)
        spacerItem3 = QtWidgets.QSpacerItem(34, 14, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem3)
        self.lineEdit_nim_nip = QtWidgets.QLineEdit(form_pengajuan)
        self.lineEdit_nim_nip.setStyleSheet("background-color: rgb(190, 190, 190);")
        self.lineEdit_nim_nip.setObjectName("lineEdit_nim_nip")
        self.horizontalLayout_6.addWidget(self.lineEdit_nim_nip)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        spacerItem4 = QtWidgets.QSpacerItem(20, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem4)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_8 = QtWidgets.QLabel(form_pengajuan)
        self.label_8.setStyleSheet("font: 75 9pt \"Arial\";")
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_7.addWidget(self.label_8)
        spacerItem5 = QtWidgets.QSpacerItem(34, 14, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem5)
        self.comboBox_prodi = QtWidgets.QComboBox(form_pengajuan)
        self.comboBox_prodi.setStyleSheet("background-color: rgb(190, 190, 190);")
        self.comboBox_prodi.setObjectName("comboBox_prodi")
        self.comboBox_prodi.addItem("")
        self.comboBox_prodi.addItem("")
        self.comboBox_prodi.addItem("")
        self.comboBox_prodi.addItem("")
        self.comboBox_prodi.addItem("")
        self.comboBox_prodi.addItem("")
        self.comboBox_prodi.addItem("")
        self.comboBox_prodi.addItem("")
        self.comboBox_prodi.addItem("")
        self.comboBox_prodi.addItem("")
        self.comboBox_prodi.addItem("")
        self.comboBox_prodi.addItem("")
        self.comboBox_prodi.addItem("")
        self.horizontalLayout_7.addWidget(self.comboBox_prodi)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        spacerItem6 = QtWidgets.QSpacerItem(20, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem6)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_9 = QtWidgets.QLabel(form_pengajuan)
        self.label_9.setStyleSheet("font: 75 9pt \"Arial\";")
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_8.addWidget(self.label_9)
        spacerItem7 = QtWidgets.QSpacerItem(34, 14, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem7)
        self.lineEdit_alamat = QtWidgets.QLineEdit(form_pengajuan)
        self.lineEdit_alamat.setStyleSheet("background-color: rgb(190, 190, 190);")
        self.lineEdit_alamat.setObjectName("lineEdit_alamat")
        self.horizontalLayout_8.addWidget(self.lineEdit_alamat)
        self.verticalLayout.addLayout(self.horizontalLayout_8)
        spacerItem8 = QtWidgets.QSpacerItem(20, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem8)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(form_pengajuan)
        self.label.setStyleSheet("font: 75 9pt \"Arial\";")
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem9)
        self.comboBox_lokasi_kunjungan = QtWidgets.QComboBox(form_pengajuan)
        self.comboBox_lokasi_kunjungan.setStyleSheet("background-color: rgb(190, 190, 190);")
        self.comboBox_lokasi_kunjungan.setObjectName("comboBox_lokasi_kunjungan")
        self.comboBox_lokasi_kunjungan.addItem("")
        self.comboBox_lokasi_kunjungan.addItem("")
        self.comboBox_lokasi_kunjungan.addItem("")
        self.comboBox_lokasi_kunjungan.addItem("")
        self.horizontalLayout.addWidget(self.comboBox_lokasi_kunjungan)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem10)
        self.verticalLayout.addLayout(self.horizontalLayout)
        spacerItem11 = QtWidgets.QSpacerItem(20, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem11)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(form_pengajuan)
        self.label_2.setStyleSheet("font: 75 9pt \"Arial\";")
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        spacerItem12 = QtWidgets.QSpacerItem(40, 18, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem12)
        self.lineEdit_alasan_datang = QtWidgets.QLineEdit(form_pengajuan)
        self.lineEdit_alasan_datang.setStyleSheet("background-color: rgb(190, 190, 190);")
        self.lineEdit_alasan_datang.setObjectName("lineEdit_alasan_datang")
        self.horizontalLayout_2.addWidget(self.lineEdit_alasan_datang)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(form_pengajuan)
        self.label_3.setStyleSheet("font: 75 9pt \"Arial\";")
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem13)
        self.lineEdit_suhu_tubuh = QtWidgets.QLineEdit(form_pengajuan)
        self.lineEdit_suhu_tubuh.setStyleSheet("background-color: rgb(190, 190, 190);")
        self.lineEdit_suhu_tubuh.setObjectName("lineEdit_suhu_tubuh")
        self.horizontalLayout_3.addWidget(self.lineEdit_suhu_tubuh)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        spacerItem14 = QtWidgets.QSpacerItem(20, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem14)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtWidgets.QLabel(form_pengajuan)
        self.label_4.setStyleSheet("font: 75 9pt \"Arial\";")
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        spacerItem15 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem15)
        self.dateTimeEdit_waktu_kunjungan = QtWidgets.QDateTimeEdit(form_pengajuan)
        self.dateTimeEdit_waktu_kunjungan.setStyleSheet("background-color: rgb(190, 190, 190);")
        self.dateTimeEdit_waktu_kunjungan.setObjectName("dateTimeEdit_waktu_kunjungan")
        self.horizontalLayout_4.addWidget(self.dateTimeEdit_waktu_kunjungan)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_9.addLayout(self.verticalLayout)
        spacerItem16 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.horizontalLayout_9.addItem(spacerItem16)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem17 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem17)
        self.btn_form_pengajuan = QtWidgets.QPushButton(form_pengajuan)
        self.btn_form_pengajuan.setStyleSheet("background-color: rgb(190, 190, 190);\n"
"font: 9pt \"Century Gothic\";")
        self.btn_form_pengajuan.setObjectName("btn_form_pengajuan")
        self.btn_form_pengajuan.clicked.connect(self.ajukan_kunjugan)

        self.verticalLayout_2.addWidget(self.btn_form_pengajuan)
        spacerItem18 = QtWidgets.QSpacerItem(17, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem18)
        self.btn_cancel_form_pengajuan = QtWidgets.QPushButton(form_pengajuan)
        self.btn_cancel_form_pengajuan.setStyleSheet("background-color: rgb(190, 190, 190);\n"
"font: 9pt \"Century Gothic\";")
        self.btn_cancel_form_pengajuan.setObjectName("btn_cancel_form_pengajuan")
        self.btn_cancel_form_pengajuan.clicked.connect(self.openHomePageFromFormPengajuan)
        self.verticalLayout_2.addWidget(self.btn_cancel_form_pengajuan)
        spacerItem19 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem19)
        self.horizontalLayout_9.addLayout(self.verticalLayout_2)

        self.retranslateUi(form_pengajuan)
        QtCore.QMetaObject.connectSlotsByName(form_pengajuan)

    def retranslateUi(self, form_pengajuan):
        _translate = QtCore.QCoreApplication.translate
        form_pengajuan.setWindowTitle(_translate("form_pengajuan", "Form"))
        self.label_5.setText(_translate("form_pengajuan", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Form Pengajuan Kunjungan Gerbang ITK</span></p></body></html>"))
        self.label_6.setText(_translate("form_pengajuan", "Nama"))
        self.label_7.setText(_translate("form_pengajuan", "NIM/NIP"))
        self.label_8.setText(_translate("form_pengajuan", "Prodi"))
        self.comboBox_prodi.setItemText(0, _translate("form_pengajuan", "Fisika"))
        self.comboBox_prodi.setItemText(1, _translate("form_pengajuan", "Matematika"))
        self.comboBox_prodi.setItemText(2, _translate("form_pengajuan", "Teknik Mesin"))
        self.comboBox_prodi.setItemText(3, _translate("form_pengajuan", "Teknik Elektro"))
        self.comboBox_prodi.setItemText(4, _translate("form_pengajuan", "Teknik Kimia"))
        self.comboBox_prodi.setItemText(5, _translate("form_pengajuan", "Teknik Material dan Metalurgi"))
        self.comboBox_prodi.setItemText(6, _translate("form_pengajuan", "Teknik Sipil"))
        self.comboBox_prodi.setItemText(7, _translate("form_pengajuan", "Perencanaan Wilayah dan Kota"))
        self.comboBox_prodi.setItemText(8, _translate("form_pengajuan", "Teknik Perkapalan"))
        self.comboBox_prodi.setItemText(9, _translate("form_pengajuan", "Sistem Informasi"))
        self.comboBox_prodi.setItemText(10, _translate("form_pengajuan", "Informatika"))
        self.comboBox_prodi.setItemText(11, _translate("form_pengajuan", "Teknik Industri"))
        self.comboBox_prodi.setItemText(12, _translate("form_pengajuan", "Teknik Lingkungan"))
        self.label_9.setText(_translate("form_pengajuan", "Alamat"))
        self.label.setText(_translate("form_pengajuan", "Lokasi Kunjungan"))
        self.comboBox_lokasi_kunjungan.setItemText(0, _translate("form_pengajuan", "Gedung A"))
        self.comboBox_lokasi_kunjungan.setItemText(1, _translate("form_pengajuan", "Gedung B"))
        self.comboBox_lokasi_kunjungan.setItemText(2, _translate("form_pengajuan", "Gedung C"))
        self.comboBox_lokasi_kunjungan.setItemText(3, _translate("form_pengajuan", "Gedung D"))
        self.label_2.setText(_translate("form_pengajuan", "Alasan Datang"))
        self.label_3.setText(_translate("form_pengajuan", "Suhu Tubuh (Gunakan .)"))
        self.label_4.setText(_translate("form_pengajuan", "Waktu Kunjungan"))
        self.btn_form_pengajuan.setText(_translate("form_pengajuan", "Submit"))
        self.btn_cancel_form_pengajuan.setText(_translate("form_pengajuan", "Cancel"))


    def show_data_inserted(self):
        message = QMessageBox()
        message.setWindowTitle('Berhasil')
        message.setText('Data telah masuk, Silahkan menunggu persetujuan')
        message.setIcon(QMessageBox.Information)
        x = message.exec_()


    def ajukan_kunjugan(self):
        try:
            mydb = mc.connect(
                host='localhost',
                user='root',
                password='',
                database='gerbang_itk'
            )

            nama = self.lineEdit_nama.text()
            nim_nip = self.lineEdit_nim_nip.text()
            prodi = self.comboBox_prodi.currentText()
            lokasi_kunjugan = self.comboBox_lokasi_kunjungan.currentText()
            alamat = self.lineEdit_alamat.text()
            suhu_tubuh = self.lineEdit_suhu_tubuh.text()
            alasan_datang = self.lineEdit_alasan_datang.text()
            waktu_kunjugan = self.dateTimeEdit_waktu_kunjungan.text()

            cursor_ajukan_kunjungan = mydb.cursor()

            query = "INSERT INTO pengunjung (nama, nip_nim, prodi, alamat, lokasi_kunjungan, alasan_datang, suhu_tubuh, waktu_kunjungan) VALUES (" + "'" + nama + "'," + "'" + nim_nip + "'," + "'" + prodi + "'," + "'" + alamat + "'," + "'" + lokasi_kunjugan + "'," + "'" + alasan_datang + "'," + "'" + suhu_tubuh + "'," +  "'" + waktu_kunjugan + "')"
            cursor_ajukan_kunjungan.execute(query)
            mydb.commit()
            mydb.close()
            self.show_data_inserted()
            self.openHomePageFromFormPengajuan()



        except:
            self.label_5.setText("Error")





if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    form_pengajuan = QtWidgets.QWidget()
    ui = Ui_form_pengajuan()
    ui.setupUiFormPengajuan(form_pengajuan)
    form_pengajuan.show()
    sys.exit(app.exec_())
